### ISSUE TITLE
Error while building on Ubuntu

### ISSUE THREAD

**Issue by SquaredWave** [tschumann/basis#2]
compilation terminated.
make[1]: *** [Makefile.hldll:211: release/obj/hldll/game_shared/modbot/bot_profile.o] Error 1
make[1]: Leaving directory '/home/square/basis-master/linux'
make: *** [Makefile:148: hl] Error 2

Missing assets.

**Comment by tschumann** [comment]
I'll try and take a look this weekend.

**Comment by tschumann** [comment]
Okay, that should be fixed now - I can build on Ubuntu with gcc 8.3.0
